// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0e4cb691-ecba-458f-aef4-756342d90d7f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onKDChange();
void onKIChange();
void onKPChange();
void onManualControlChange();
void onSetPointChange();
void onBalanceModeChange();
void onCalibrateIMUStateChange();
void onForwardInputChange();
void onImuCalibratedChange();
void onReverseInputChange();
void onRotateLeftInputChange();
void onRotateRightInputChange();

float kD;
float kI;
float kP;
float manualControl;
float pitchAngle;
float setPoint;
bool balanceMode;
bool calibrateIMUState;
bool forwardInput;
bool imuCalibrated;
bool reverseInput;
bool rotateLeftInput;
bool rotateRightInput;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(kD, READWRITE, ON_CHANGE, onKDChange);
  ArduinoCloud.addProperty(kI, READWRITE, ON_CHANGE, onKIChange);
  ArduinoCloud.addProperty(kP, READWRITE, ON_CHANGE, onKPChange);
  ArduinoCloud.addProperty(manualControl, READWRITE, ON_CHANGE, onManualControlChange);
  ArduinoCloud.addProperty(pitchAngle, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(setPoint, READWRITE, ON_CHANGE, onSetPointChange);
  ArduinoCloud.addProperty(balanceMode, READWRITE, ON_CHANGE, onBalanceModeChange);
  ArduinoCloud.addProperty(calibrateIMUState, READWRITE, ON_CHANGE, onCalibrateIMUStateChange);
  ArduinoCloud.addProperty(forwardInput, READWRITE, ON_CHANGE, onForwardInputChange);
  ArduinoCloud.addProperty(imuCalibrated, READWRITE, ON_CHANGE, onImuCalibratedChange);
  ArduinoCloud.addProperty(reverseInput, READWRITE, ON_CHANGE, onReverseInputChange);
  ArduinoCloud.addProperty(rotateLeftInput, READWRITE, ON_CHANGE, onRotateLeftInputChange);
  ArduinoCloud.addProperty(rotateRightInput, READWRITE, ON_CHANGE, onRotateRightInputChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
